local set = vim.opt
set.guicursor = ''
set.number = true
set.tabstop = 2
set.softtabstop = 2
set.shiftwidth = 2
set.smartindent = true
set.ambw = 'double'
set.undodir = os.getenv("HOME") .. "/.vim/undodir"
set.undofile = true
set.mouse = 'a'
set.autoread = true
set.laststatus = 2
set.tw = 120
set.autoread = true
set.showmode = false
set.signcolumn = 'yes'
-- set.clipboard = 'unnamed'
set.backup = false
set.writebackup = false
set.updatetime = 50
set.scrolloff = 10
set.spelllang = 'en_ca'
set.hlsearch = true
set.incsearch = true
set.termguicolors = true
set.cursorline = true
